version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - go
    cooldown:
      default-days: 2
    groups:
      aws:
        patterns:
        - "github.com/aws/aws-sdk-go-v2*"
      golang-x:
        patterns:
        - "golang.org/x/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github-actions
    cooldown:
      default-days: 2
    groups:
      actions:
        patterns:
        - "actions/*"
