inputs:
  version:
    description: "A version to install ecschedule"
    default: "v0.11.3"
runs:
  using: "composite"
  steps:
  - run: |
      TEMP_PATH="$(mktemp -d)"
      curl -sfL https://raw.githubusercontent.com/Songmu/ecschedule/main/install.sh | sh -s -- -b "${TEMP_PATH}" "${{ inputs.version }}" 2>&1
      sudo mv ${TEMP_PATH}/ecschedule /usr/local/bin/ecschedule
      rm -rf ${TEMP_PATH}
    shell: bash
