name: release
description: release ecschedule
inputs:
  tag:
    description: tag name to be released
    default: ''
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
  - name: setup go
    uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
    with:
      go-version-file: go.mod
  - name: crossbuild
    run: make crossbuild
    shell: bash
  - name: upload
    uses: tcnksm/ghr@766f869eacbbb086e8860cf0f0192dda6e8e67e1 # v0.18.3
    with:
      tag: ${{ inputs.tag || github.ref_name }}
      path: dist
      token: ${{ inputs.token }}
